---
# Source: fiter-app/charts/community-app/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fineract-community-app
  namespace: fineract-dev
  labels:
    app.kubernetes.io/name: community-app
    app.kubernetes.io/instance: fineract
    app_name: community-app