apiVersion: v1
kind: Service
metadata:
  name: fineract-nginx
  namespace: fineract-dev
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: fineract-nginx
